"""Pydantic models – Drift patterns, signals, and classifications."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ── Drift Pattern Enum ───────────────────────────────
class DriftPatternType(str, Enum):
    FATIGUE = "Fatigue"
    OVERCONFIDENCE = "Overconfidence"
    HURRY = "Hurry"
    QUIET_FEAR = "Quiet_Fear"
    HOARDING = "Hoarding"
    COMPLIANCE_THEATER = "Compliance_Theater"


# ── NIST Controls ────────────────────────────────────
class NISTControl(str, Enum):
    AC_2 = "AC-2"   # Account Management
    AU_6 = "AU-6"   # Audit Review
    IR_6 = "IR-6"   # Incident Reporting
    CA_7 = "CA-7"   # Continuous Monitoring
    AT_2 = "AT-2"   # Security Awareness Training


# ── Severity & Alert Levels ──────────────────────────
class Severity(int, Enum):
    """1-5 scale mirroring NIST severity levels."""
    MINIMAL = 1
    LOW = 2
    MODERATE = 3
    HIGH = 4
    CRITICAL = 5


class AlertLevel(str, Enum):
    WATCH = "Watch"
    WARNING = "Warning"
    CRITICAL = "Critical"


# ── Signal Models ────────────────────────────────────
class SignalType(str, Enum):
    ACCESS_LOG = "access_log"
    AUDIT_REVIEW = "audit_review"
    INCIDENT_RESPONSE = "incident_response"
    COMMUNICATION = "communication"
    APPROVAL_WORKFLOW = "approval_workflow"
    TRAINING_COMPLETION = "training_completion"
    CUSTOM = "custom"


class RawSignal(BaseModel):
    """Incoming organizational signal before classification."""
    id: UUID = Field(default_factory=uuid4)
    signal_type: SignalType
    source: str
    timestamp: datetime
    data: Dict
    domain: str = "enterprise"
    metadata: Dict = Field(default_factory=dict)


class ProcessedSignal(BaseModel):
    """Signal after anonymization and enrichment."""
    id: UUID = Field(default_factory=uuid4)
    raw_signal_id: UUID
    signal_type: SignalType
    timestamp: datetime
    features: Dict
    team_id: Optional[str] = None
    system_id: Optional[str] = None
    anonymized: bool = True


# ── Classification Models ────────────────────────────
class DriftClassification(BaseModel):
    """Single drift pattern classification result."""
    pattern: DriftPatternType
    confidence: float = Field(ge=0.0, le=1.0)
    severity: Severity
    signals_used: List[UUID] = Field(default_factory=list)
    nist_controls_at_risk: List[NISTControl] = Field(default_factory=list)
    temporal_weight: float = Field(default=1.0, ge=0.0)
    reasoning: str = ""
    requires_human_review: bool = False

    def model_post_init(self, __context) -> None:
        if self.confidence < 0.70:
            self.requires_human_review = True


class DriftReport(BaseModel):
    """Complete structured JSON drift report – pipeline output."""
    id: UUID = Field(default_factory=uuid4)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    domain: str
    team_id: Optional[str] = None
    system_id: Optional[str] = None
    active_patterns: List[DriftClassification] = Field(default_factory=list)
    alert_level: AlertLevel = AlertLevel.WATCH
    acceleration_detected: bool = False
    acceleration_details: Optional[str] = None
    routing_decision: str = "log"
    calibration_response_id: Optional[UUID] = None
    metadata: Dict = Field(default_factory=dict)


# ── Alert Model ──────────────────────────────────────
class AlertStatus(str, Enum):
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    ACTED_UPON = "acted_upon"


class Alert(BaseModel):
    """Alert generated by the early warning engine."""
    id: UUID = Field(default_factory=uuid4)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    alert_level: AlertLevel
    drift_patterns: List[DriftClassification]
    team_id: Optional[str] = None
    system_id: Optional[str] = None
    domain: str
    nist_controls_at_risk: List[NISTControl] = Field(default_factory=list)
    severity_score: Severity = Severity.MINIMAL
    confidence_score: float = 0.0
    signals_summary: str = ""
    plain_language_explanation: str = ""
    calibration_recommendation: Optional[str] = None
    calibration_response_id: Optional[UUID] = None
    acceleration_flag: bool = False
    acceleration_details: Optional[str] = None
    status: AlertStatus = AlertStatus.ACTIVE
    human_approved: bool = False
    acted_upon_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    resolved_by: Optional[str] = None


# ── Calibration Models ───────────────────────────────
class ApprovalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    REVISION_REQUESTED = "revision_requested"


class CalibrationResponse(BaseModel):
    """NI calibration response from the 1000 Namas library."""
    id: UUID = Field(default_factory=uuid4)
    drift_pattern: DriftPatternType
    severity_range: List[int] = Field(default_factory=lambda: [1, 5])
    organizational_context: str = ""
    role_context: str = ""
    moment_context: str = ""
    response_text: str
    is_placeholder: bool = False
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    approved_by: Optional[str] = None
    approved_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    effectiveness_score: Optional[float] = None
    delivery_count: int = 0
    acknowledged_count: int = 0
    acted_upon_count: int = 0


class CalibrationDelivery(BaseModel):
    """Record of a calibration response delivery."""
    id: UUID = Field(default_factory=uuid4)
    response_id: UUID
    alert_id: UUID
    delivered_at: datetime = Field(default_factory=datetime.utcnow)
    delivery_method: str = "dashboard"
    acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None
    acted_upon: bool = False
    acted_upon_at: Optional[datetime] = None


# ── User & Role Models ──────────────────────────────
class UserRole(str, Enum):
    COMPLIANCE_OFFICER = "compliance_officer"
    CISO = "ciso"
    NI_ARCHITECT = "ni_architect"
    ADMIN = "admin"
    VIEWER = "viewer"


class User(BaseModel):
    """User model."""
    id: UUID = Field(default_factory=uuid4)
    email: str
    full_name: str
    role: UserRole
    organization: str
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Audit Log ────────────────────────────────────────
class AuditAction(str, Enum):
    ALERT_GENERATED = "alert_generated"
    ALERT_ACKNOWLEDGED = "alert_acknowledged"
    ALERT_ESCALATED = "alert_escalated"
    ALERT_RESOLVED = "alert_resolved"
    ALERT_ACTED_UPON = "alert_acted_upon"
    CALIBRATION_DELIVERED = "calibration_delivered"
    CALIBRATION_ACKNOWLEDGED = "calibration_acknowledged"
    CALIBRATION_APPROVED = "calibration_approved"
    CALIBRATION_REJECTED = "calibration_rejected"
    HUMAN_REVIEW_APPROVED = "human_review_approved"
    HUMAN_REVIEW_REJECTED = "human_review_rejected"
    NIST_MAPPING_ADDED = "nist_mapping_added"
    NIST_MAPPING_APPROVED = "nist_mapping_approved"
    DOMAIN_CONFIG_UPLOADED = "domain_config_uploaded"
    SIGNAL_INGESTED = "signal_ingested"
    DATA_PURGED = "data_purged"
    SYSTEM_CONFIG_CHANGED = "system_config_changed"


class AuditEntry(BaseModel):
    """Immutable audit log entry."""
    id: UUID = Field(default_factory=uuid4)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    action: AuditAction
    actor: Optional[str] = None  # "system" or user email
    resource_type: str = ""
    resource_id: Optional[UUID] = None
    details: Dict = Field(default_factory=dict)
    ip_address: Optional[str] = None

    class Config:
        frozen = True  # Immutable
